### ISSUE TITLE
npm commands like install should work as well

### ISSUE THREAD

**Issue by novascreen** [gyandeeps/hypernpm#1]
The default command for `ALT + 1` is `install`, it results in running `npm run install` which doesn't seem to be the desired behavior. `npm run test` works as well as `npm test`, but it doesn't work for `install` or other npm commands.
So it would be nice if this could detect npm commands and omit the `run` when executing the configured script/command.

**Comment by gyandeeps** [comment]
Are you saying (in general) `npm install` vs `npm run install` have different behavior?
SAme above question for `test`?

**Comment by gyandeeps** [comment]
Ah you are right. Do you want to send a PR for this @novascreen ?
